# Runs `cargo-deny` when modifying `Cargo.lock`.

name: deny

on:
  push:
    branches: [v1.1.0]
    paths: [Cargo.lock]
  pull_request:
    branches: [v1.1.0]
    paths: [Cargo.lock]
  merge_group:

env:
  CARGO_TERM_COLOR: always

concurrency: deny-${{ github.head_ref || github.run_id }}

jobs:
  deny:
    name: deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check all
